### ISSUE TITLE
Scrolling occasionally freezes after tapping on screen

### ISSUE THREAD

**Issue by jgw96** [driftyco/ionic-v1#155]
_From @cnnrmtthws on March 24, 2016 12:57_

#### Short description of the problem:

On an iPhone 6, iOS 9.2, tapping on the screen while scrolling can cause the scrollable content to freeze in place. The scrollbar on the right, will continue to move up/down when performing the scroll gesture but the content remains frozen in place. Leaving the view clears the issue.

I have managed to reproduce this on a blank starter app with a scrollable ion-content. And can reproduce this with both native and js scrolling.
![scrollfreeze](https://cloud.githubusercontent.com/assets/14077658/14017501/b83fa1a0-f1bf-11e5-8a97-b5296b63de99.gif)

I have attached a zip with the code.
[scrolltest.zip](https://github.com/driftyco/ionic/files/187852/scrolltest.zip)

I have also created a [codepen](http://codepen.io/anon/pen/VabGOj) if that's easier, though I cannot reproduce the issue through the browser.
#### What behavior are you expecting?

Content not to freeze in place and to be able to continue to scroll the content

**Steps to reproduce:**
1. Scroll the page up and down
2. Keep tapping on the header (it doesn't have to be the header but I find this is the easiest way to reproduce) while scrolling.
3. Content will eventually freeze in place.
4. Scrollbars will continue to act as though the content is scrolling

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
I suspect that this issue (https://github.com/driftyco/ionic/issues/5806) is related as though the steps to reproduce are different, the result is similar.

**Which Ionic Version?** 1.x

**Run `ionic info` from terminal/cmd prompt:** (paste output below)
Your system information:

Cordova CLI: 6.0.0
Gulp version:  CLI version 3.9.0
Gulp local:  
Ionic Version: 1.2.4
Ionic CLI Version: 1.7.14
Ionic App Lib Version: 0.7.0
ios-deploy version: 1.8.4 
ios-sim version: 5.0.3 
OS: Mac OS X El Capitan
Node Version: v0.12.7
Xcode version: Xcode 7.2.1 Build version 7C1002 

_Copied from original issue: driftyco/ionic#5932_

**Comment by jgw96** [comment]
Hello! Thanks for opening an issue with us! Are you seeing this in the browser, ios emulator or on android too? Also, if you have another ios device can you reproduce it there too?

**Comment by jgw96** [comment]
_From @cnnrmtthws on March 24, 2016 16:39_

Hi. I have reproduced the issue on an iPad 2 iOS 9.2 but was not able to reprodue the issue on an iPad mini with iOS 8.4. I also haven't been able to reproduce this in the browser or on Android so far. I haven't had much luck getting the ios simulator to actually work properly to check there.

**Comment by jgw96** [comment]
@cnnrmtthws Thanks for the info! Are you having issues with the ionic emulate ios command?

**Comment by jgw96** [comment]
_From @cnnrmtthws on March 29, 2016 12:35_

@jgw96 Hi sorry, I was having an issue where the simulator wouldn't launch but it seems to be working fine this week. I haven't been able to reproduce the issue in the simulator using the steps above, but that may be due to it being more difficult with only a single mouse pointer rather than being able to use multiple fingers. I have managed to reproduce it in the simulator (and on device) by repeatedly tapping the status bar to scroll up when momentum scrolling.

**Comment by jgw96** [comment]
_From @danbucholtz on April 11, 2016 20:7_

@cnnrmtthws, I am having a hard time reproducing this.  I have downloaded the zip file and ran that on my iPhone 6S, and then I also pulled down the codepen and tried that as well for good measure.  When you're tapping on the header, are you tapping while the intertia scrolling is happening, or while your other finger is actively dragging the content up or down?  I have tried both.  I have also tried slow, rhythmic tapping on the header, and tapping rapid fire.  I have tried this for about 5 minutes or scrolling up and down.  Does it typically take a while to reproduce?  Does this happen on iPad, iPhone or both?

Any additional suggestions on how to recreate?  FWIW, I am running iOS 9.3.1, which is the latest iOS.

Thanks,
Dan

**Comment by jgw96** [comment]
_From @cnnrmtthws on April 12, 2016 13:55_

@danbucholtz I think its when the intertia scrolling is happening. I have not found it to be immediate but certainly not more than a couple of minutes max. I have managed to reproduce on both an iPhone 6 and on an iPad 2.

I can reproduce a hang almost imediately by scrolling and while the inertia scrolling is happening and double/tripple tapping the status bar rapidly, which trigger the scroll to the top. I find that this causes the scroll to be stuck more often than not after that point. I am not sure if this is a different issue though.

**Comment by jgw96** [comment]
_From @danbucholtz on April 12, 2016 16:0_

@cnnrmtthws, I can't reproduce on my device (6S) or with the simulator of an iPhone 6.  Any ideas?

![gif of process](http://g.recordit.co/jCmcSdrIlj.gif)

**Comment by jgw96** [comment]
_From @cnnrmtthws on April 14, 2016 19:47_

@danbucholtz Hmm I have been able to reproduce it on the simulator as well as the iphone 6. After rapidly tapping the status bar at the top I tend to see a white flash as well. I will try and capture a video of reproducing it the simulator as you have done.

**Comment by jgw96** [comment]
@cnnrmtthws did you ever get a chance to get that video together? I just did some more tests using the ios simulator emulating an iphone 6 running ios 9.3 and an Iphone 5 running ios 9.3 and could not reproduce it either unfortunately.

**Comment by jgw96** [comment]
_From @cnnrmtthws on April 22, 2016 13:50_

@jgw96 sorry just recorded it now. I can still reproduced. I upgraded the iphone 6 to 9.3 to make sure that wasn't the issue and I can still reproduce it there. I also tried building through the ionic platform build, rather than locally, and I was also able to reproduce the issue with that version.
![frozen-scroll-simulator](https://cloud.githubusercontent.com/assets/14077658/14743352/1c0c3d02-0899-11e6-8902-242a1d0835ac.gif)

**Comment by jgw96** [comment]
_From @danbucholtz on April 22, 2016 14:4_

@cnnrmtthws, Cool.  We'll take another look when we have some time.  Is there anything that you think we could be missing or doing wrong?

**Comment by jgw96** [comment]
_From @cnnrmtthws on April 22, 2016 14:12_

I can't think of anything, the steps i was using look like the same steps that you were using in your video, i.e momentum scrolling and then rapidly tap status bar results in the scroll being frozen. The fact that you haven't been able to reproduce makes me wonder if something is wrong with my environment, hence my trying the build with the ionic platform service.

**Comment by jgw96** [comment]
Hello @cnnrmtthws ! Are you still having this issue?

**Comment by jgw96** [comment]
Hello all! As it seems it has been a while since there was any activity on this issue i will be closing it for now. Feel free to comment if you are still running into this issue. Thanks for using Ionic!

**Comment by jgw96** [comment]
_From @tlancina on May 14, 2016 15:32_

Ran into this a few times with the scroll triggered by the keyboard as well. It seems to be when the scroll view is already in motion and something else programmatically triggers scroll (like the keyboard or the status bar tap). 

Thanks to @cnnrmtthws I can reliably repro using https://github.com/driftyco/ionic/issues/5932#issuecomment-213437102 on a 5s by starting a scroll and then spam clicking the status bar (sometimes it takes a few tries).

**Comment by jgw96** [comment]
_From @yazantahhan on August 23, 2016 11:40_

Hey guys,
I had the same issue. I was setting the default jsScrolling to false. What I did is: I set the jsScrolling to true `$ionicConfigProvider.scrolling.jsScrolling(true)` in the config part.

**Comment by jgw96** [comment]
_From @ShawnXu on September 29, 2016 18:42_

Is there an equivalent approach to jsScrolling in ionic 2?

**Comment by jgw96** [comment]
Hello all! Is this an issue with our fork of the [WkWebview plugin](https://github.com/driftyco/cordova-plugin-wkwebview-engine#installation-instructions)?

**Comment by jgw96** [comment]
_From @leschirmeur on October 4, 2016 16:28_

To me this seems to be a similar issue as the one described in #5806 which we are dealing with using a custom directive, see my comment https://github.com/driftyco/ionic/issues/5806#issuecomment-203867400

Under some circumstances, overflow-scroll is set to "hidden" but not set back to "scroll" anymore which makes the screen freeze. The reason for this is unknown to me, we experienced it a lot when opening and closing the keyboard, hence the custom directive I mentioned above.

Maybe this helps in investigating this issue...

**Comment by jgw96** [comment]
_From @saurabhudaniya200 on January 6, 2017 10:14_

I saw that after tapping on the statusbar multiple times the ion-content gets inline style set to overflow:hidden(this is required to fix the -webkit-overflow-scrolling issue I guess), I did the following things to fix it.


1) setting !important to overflow-scroll

```
.overflow-scroll{
  overflow-y:scroll!important;
}
```

2) Added one more class called hideScroll

```
.overflow-scroll.hideScroll{
    overflow:hidden;
    overflow-y:hidden!important;
}

```

3) handled the statusTap event in the application itself like below.

```
window.addEventListener("statusTap", function() {
                        var ionContents = angular.element(document.querySelectorAll('ion-content.overflow-scroll'));
                            angular.forEach(ionContents, function(elem){
                                var elm = angular.element(elem)
                                elm.addClass('hideScroll');
                            });                            
                            $ionicScrollDelegate.scrollTop(true);
                            $timeout(function(){
                                angular.forEach(ionContents, function(elem){
                                    var elm = angular.element(elem)
                                    elm.removeClass('hideScroll');
                                 });
                            }, 500)
                    });
```
This is working fine now as expected

**Comment by mashah1** [comment]
I am still having above issue even after trying this above solution, may I know what needs to be set on ion-content? I have set jsScrolling(true) in config and in my template I have <ion-content overflow-scroll="true"> and I have added .overflow-scroll{
  overflow-y:scroll!important;
} .overflow-scroll.hideScroll{
    overflow:hidden;
    overflow-y:hidden!important;
}
 in my style.css and window.addEventListener("statusTap", function() {
                        var ionContents = angular.element(document.querySelectorAll('ion-content.overflow-scroll'));
                            angular.forEach(ionContents, function(elem){
                                var elm = angular.element(elem)
                                elm.addClass('hideScroll');
                            });                            
                            $ionicScrollDelegate.scrollTop(true);
                            $timeout(function(){
                                angular.forEach(ionContents, function(elem){
                                    var elm = angular.element(elem)
                                    elm.removeClass('hideScroll');
                                 });
                            }, 500)
                    }); 

in my app.js. But I still have an issue. Please help ASAP its really urgent

**Comment by saurabhudaniya200** [comment]
@mashah1 There is one more statusTap event in ionic.bundle you may have to comment it out first as in the above implementation the $ionicScrollDelegate.scrollTop(true); is already added and also try with setting jsscrolling to false

**Comment by mashah1** [comment]
@saurabhudaniya200 my statusTap event is not getting called at all. I added few console to this event to make sure if its getting called. But statusTap is not getting called. I added this event in my app.js. I added like this: not sure if its wrong?
<ion-content class="has-header overflow-scroll hideScroll">
    <div class="list">

My problem is:
1. I have input box inside <ion-item> tag with ng-repeat. I am listing near about 150 items in one page.
2. When I tap into input box it focuses quickly initially but after sometime suppose it reached 100 items, there is lag/delay in focusing on input box and which freezes the app completely. Please help ASAP.

I have tried $ionicConfigProvider.scrolling.jsScrolling(false); and also with true boolean

NOTE: This is issue only happens in iOS devices like iPad mini and iPhones, but not on Android.

Please help ASAP. Thanks! Its really urgent to fix

**Comment by davixz** [comment]
Hey guys,

Following jgw96 i pasted this into my styles.css and the issue did not apeared again.

.overflow-scroll {
    overflow: scroll !important;
    overflow-x: hidden !important;
    overflow-y: scroll !important;
}

**Comment by jodybrewster** [comment]
Hey this issue is in Ionic V2 as well.

**Comment by jodybrewster** [comment]
Actually @jgw96 this is fixed when I use the ionic wk plugin but the question I have is why?  Why is this here?  It seems like whatever stop scrolling you're doing here is counter productive if you're going PWA since this issue happens on safari.   Anyway if you can give me some insight as to why this is happening I'd appreciate it.   My implementation is outputting from platform browser but I run it in a custom wkwebview on an existing app.  Please let me know thanks.

**Comment by jodybrewster** [comment]
Just a quick update, I fixed it by adding   self.webView.scrollView.bounces = NO;  It seems like the bouncing in ios causes ionic to freeze up.

**Comment by eongoo** [comment]
https://stackoverflow.com/questions/26176288/webkit-overflow-scrolling-touch-breaks-in-apples-ios8?answertab=votes#tab-top

-webkit-transform: translateZ(0px);
-webkit-transform: translate3d(0,0,0);
-webkit-perspective: 1000;

"Addendum: I did, however, have to point out to our client that if even with this fix the user starts trying to scroll on a non-scrollable element she will have to wait a second after stopping before being able to scroll the scrollable element. This is native behaviour."

**Comment by MrDrProfX** [comment]
I'm still seeing this issue. None of the above solutions really make sense to me.

In the latest IOS Safari, when I tap on the screen shortly after scrolling (only when the screen is bouncing at the top and bottom) the scroll freezes. I can't scroll anymore.

This issue is seen very frequently and completely breaks the usability of the app.

From my research, I guess I cannot disable scroll bouncing because it's natively how IOS handles scrolling.

I don't know what to do.

**Comment by mvasin** [comment]
I don't use Ionic, but I suffer the same issue. I made up a reproduction demo https://codesandbox.io/s/1qz8v5q5wq that you can open in Safari on an iOS device at https://1qz8v5q5wq.codesandbox.io/

Just an overflowed fixed div with `scroll` and `-webkit-overflow-scrolling` enabled.

I tried on iPhone 6 and on iPad mini 2, both running iOS 11.4.1.

Pull further at the top or at the bottom a few times to bounce the page, and there you have it, scrolling freezes for a few seconds.

**Comment by wes-r** [comment]
I too don't use Iconic but ran into a similar issue. (@mvasin I think this is the same thing you are hitting).

For me, the freezing was repeatable and happened when trying to scroll up or down when already at the top or bottom, respectively. The fix was to add some listeners for `touchstart` and `touchmove` and detect these cases and `event.preventDefault()` on ’em.

Something like:
```js
var lastY = 0; // Needed in order to determine direction of scroll.
$(".scroll-container").on('touchstart', function(event) {
    lastY = event.touches[0].clientY;
});

$('.scroller').on('touchmove', function(event) {
    var top = event.touches[0].clientY;

    // Determine scroll position and direction.
    var scrollTop = $(event.currentTarget).scrollTop();
    var direction = (lastY - top) < 0 ? "up" : "down";

    // FIX IT!
    if (scrollTop == 0 && direction == "up") {
      // Prevent scrolling up when already at top as this introduces a freeze.
      event.preventDefault();
    } else if (scrollTop >= (event.currentTarget.scrollHeight - event.currentTarget.outerHeight()) && direction == "down") {
      // Prevent scrolling down when already at bottom as this also introduces a freeze.
      event.preventDefault();
    }

    lastY = top;
});
```

I hope this helps the next poor soul that encounters this horrible bug! Good luck and keep fighting!

**Comment by mvasin** [comment]
Hi @wes-r! This looks promising, I tried to apply your fix, but got stuck - the scroll is always prevented on iOS. Can you please have a look? https://codesandbox.io/s/3080ljnq5q (open https://3080ljnq5q.codesandbox.io/ on iOS)

**Comment by mvasin** [comment]
Wow, it really fixes this annoying bug! 🎉 @wes-r I just can't thank you enough!

The whole layout of my current project relies on scrolling in fixed containers, and when I discovered the bug it ruined a few weeks of my work.

The absence of the bounce effect when already at the top / bottom also feels a bit like a glitch, but it's a minor one, an acceptable trade-off.

Could you also share your solution (describe and provide the link to codesandbox) on [StackOverflow](https://stackoverflow.com/questions/39692337/div-scrolling-freezes-sometimes-if-i-use-webkit-overflow-scrolling)? I'm sure it will help _a lot_ of people.

**Comment by Aarbel** [comment]
**Stable fix for me** 

=> [Check my post on stackoverflow](https://stackoverflow.com/a/53458602/10699076)

Solution is to use [body-scroll-lock package](https://www.npmjs.com/package/body-scroll-lock)

**Comment by Scobee** [comment]
@Aarbel - how can I use this on my entire ionic 3 app ? Since this is happening in all my tabs ?

**Comment by Aarbel** [comment]
@Scobee 
I applied this library on scrolling elements (popups, contents, etc...). 
My <body> is fixed and not scrolling.

**Comment by Scobee** [comment]
@Aarbel - can you give me an example on how you applied it to the <ion-content> please ?

**Comment by Aarbel** [comment]
I saw that the origin of this freezing problem was due to `fixed` body. Many developers remove overscroll/bouncing on iOS with this trick (see [this article](https://www.bram.us/2016/05/02/prevent-overscroll-bounce-in-ios-mobilesafari-pure-css/) ).

[body-scroll-lock](https://www.npmjs.com/package/body-scroll-lock) avoids to set `position: fixed` to the body and dynamically hacks the iOS body bouncing with Javascript when a targeted element is scrolling.

**CSS**
```CSS
body {
    overflow: hidden;
    position: static;
    display: block;
}

/* Element to scroll without body bouncing on ios */
#element-to-scroll {
    overflow-y: scroll;
}
```

**REACT**
```JS
import PropTypes from 'prop-types';
import React from 'react';
import { disableBodyScroll } from 'body-scroll-lock';


class MyComponent extends React.Component {
    componentDidMount() {
        disableBodyScroll(
            document.getElementById('element-to-scroll'),
			/* BodyScroll Option : allow Textarea scrolling */
            { allowTouchMove: el => (el.tagName === 'TEXTAREA') }
        );
    }

    render() {
        return (
            <div
                id="element-to-scroll"
            >
                …
            </div>
        )
    }
}
```

**Comment by kapilSoni101** [comment]
@Aarbel  sir i have got same issue that is occur @mvasin but sir in the iphone7 the top or at the bottom a few times to bounce the page, and scrolling freezes for a few seconds but issue is occur only in the iphone7 but in another iphone devices its worked and i am using ionic3 sir?

**Comment by Aarbel** [comment]
I don't use Ionic, so maybe css bad settings for the native webview.

**Comment by kapilSoni101** [comment]
it ok sir do you have any idea sir how to fix scolling issue?

**Comment by Aarbel** [comment]
the only way i've found was using body-scroll lock.
The rest is pure css settings, check if you don't over-use fixed elements, or scrolling elements etc...

**Comment by kapilSoni101** [comment]
No sir..i am not using fixed element but i have used only overflow-scoll property in scroll-content section..ok sir i will use body- scroll lock and then let y know after use this.thank you sir.

**Comment by jonasnordlund** [comment]
This is still a thing here in iOS 12 and Ionic 4 already on the stock `ionic start myApp tabs` when tapping either the picture or the "Welcome to Ionic" header text. Pretty disheartening. You can eventually break out of it by trying to tap on other elements but end users will think the app simply keeps freezing.

**Comment by kapilSoni101** [comment]
Finally scrolling issue fixed for me after add below css in the app.scss:

ion-app.platform-ios12 ion-content { pointer-events: auto; /*fix scroll lock on ios12.2*/ }

**Comment by vicenterusso** [comment]
> Finally scrolling issue fixed for me after add below css in the app.scss:
> '
> ion-app.platform-ios12 ion-content { pointer-events: auto; /_fix scroll lock on ios12.2_/ }
> '

thank you @kapilSoni101 .. fixed!

**Comment by maxime-guyot** [comment]
Thanks you @kapilSoni101 !
You saved my day ❤️👍
@apple WTF ?!

**Comment by kapilSoni101** [comment]
> > Finally scrolling issue fixed for me after add below css in the app.scss:
> > '
> > ion-app.platform-ios12 ion-content { pointer-events: auto; /_fix scroll lock on ios12.2_/ }
> > '
> 
> thank you @kapilSoni101 .. fixed!

welcome sir....

**Comment by kapilSoni101** [comment]
> Thanks you @kapilSoni101 !
> You saved my day ❤️👍
> @apple WTF ?!

welcome sir...

**Comment by ronaldso55** [comment]
> Finally scrolling issue fixed for me after add below css in the app.scss:
> '
> ion-app.platform-ios12 ion-content { pointer-events: auto; /_fix scroll lock on ios12.2_/ }
> '

Does anyone here use Meteor 1.x and Ionic 1 and hit into this issue?  Where is the exact location I should put this CSS to get around the scroll lock issue?

Thanks in advanced.

**Comment by ronaldso55** [comment]
Just for reference for folks who use ionic 1.  Issues solved by following: https://github.com/ionic-team/ionic-v1/issues/400

**Comment by cleverappdesign** [comment]
> Finally scrolling issue fixed for me after add below css in the app.scss:
> '
> ion-app.platform-ios12 ion-content { pointer-events: auto; /_fix scroll lock on ios12.2_/ }
> '

You saved my day! having this issue for ionic 3 as well. Got it working after using your solution.
